# Generated by Django 2.2 on 2022-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menu_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifticon',
            name='category',
            field=models.CharField(choices=[('음료', '음료'), ('푸드', '푸드'), ('상품', '상품')], max_length=80),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('음료', '음료'), ('푸드', '푸드'), ('상품', '상품')], max_length=80),
        ),
    ]
